モジュール名の定義間違いを修正 公式のUsageをコピペした時に気づいた
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel-preset-env/babel-preset'
Require stack:
- /Users/satoshi.hirata/my_projects/webpack_sample/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/satoshi.hirata/my_projects/webpack_sample/node_modules/@babel/core/lib/config/files/index.js